[package]
name = "magic_square"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.16.1"
rand = "0.9.0"
rayon = "1.10.0"
